/* ─────────────────────────────────────────────────────────────────
   BENOT Platform — Shared type definitions
   ─────────────────────────────────────────────────────────────── */

// ── Product ──────────────────────────────────────────────────────
export type ProductType =
  | "premium_custom"      // Camiseta personalizada (color + frase + diseño)
  | "running_fullprint"   // Camiseta multideporte 100% fullprint personalizada
  | "solidary_standard";  // Camiseta solidaria #YoTeEmpujo

export const PRODUCT_TYPE_NAMES: Record<ProductType, string> = {
  premium_custom:    "Camiseta personalizada premium",
  running_fullprint: "Camiseta multideporte 100% fullprint personalizada",
  solidary_standard: "Camiseta personalizada estándar",
};

// ── Order lifecycle ───────────────────────────────────────────────
export type OrderStatus =
  | "pending"          // sesión Stripe creada, no pagada
  | "paid"             // pago confirmado por webhook
  | "production_sent"  // email enviado al proveedor
  | "in_production"    // proveedor ha confirmado recepción
  | "shipped"          // en camino
  | "delivered";       // entregado

// ── Per-item production status ───────────────────────────────────
// Decoupled from Order.status so multi-provider orders can track
// each item independently through the production pipeline.
export type ProductionStatus =
  | "pending"    // awaiting provider assignment / confirmation
  | "queued"     // queued for printing
  | "printing"   // currently being produced
  | "completed"  // production done, ready for shipping
  | "shipped";   // dispatched to customer

// ── Sizes map ────────────────────────────────────────────────────
export type SizeMap = Record<string, number>;

// ── Print zone ───────────────────────────────────────────────────
// A named area of the garment that receives an independent design.
// Add new zoneIds as needed — the rest of the system adapts automatically.
//
// Known zone IDs (extend freely):
//   "front"        – Diseño delantero
//   "back"         – Diseño trasero
//   "right_sleeve" – Manga derecha (siempre logo B de BENOT)
//   "left_sleeve"  – Manga izquierda  (reservado)
//   "neck_label"   – Etiqueta interior (reservado)
//   "side_panel"   – Panel lateral     (reservado)
export interface PrintZone {
  zoneId:   string;   // unique identifier for the zone
  label:    string;   // human-readable label in Spanish (used in emails + PDF)
  code:     string;   // asset filename stem (without extension)
  isFixed?: boolean;  // true = non-configurable zone (e.g. always the BENOT logo)
}

// ── Frozen asset ─────────────────────────────────────────────────
// Immutable snapshot of a design file at the moment of purchase.
// Copied to /data/orders/{orderRef}/ so future asset updates in
// the configurador never affect past orders.
export interface FrozenAsset {
  cartItemIndex: number;   // which CartItem this asset belongs to
  zoneId?:       string;   // zone this asset covers (if applicable)
  label:         string;   // human-readable label  ("Diseño delantero", etc.)
  filename:      string;   // filename used in the order folder & email attachments
  absolutePath:  string;   // frozen copy path: /app/data/orders/BN-xxx/filename
  originalPath:  string;   // source path at time of purchase (for audit trail)
}

// ── Cart items (front-end payload, preserved 1:1) ─────────────────
export interface CartItemPersonalizada {
  tipo:            "personalizada";
  color:           string;
  fraseCode:       string;
  disenoCode:      string;
  disenoCategoria: string;
  sizes:           SizeMap;
}

// Running fullprint: each print zone is stored independently.
// The right sleeve always contains the BENOT "B" logo (isFixed: true).
// finalPreview is the composite mockup generated by the configurador.
export interface CartItemRunning {
  tipo:           "running";
  zones:          PrintZone[];
  finalPreview?:  string;   // asset code for the final composite render
  sizes:          SizeMap;
}

// Solidary (yoteempujo): single fixed design, no zone breakdown needed.
export interface CartItemSolidary {
  tipo:  "yoteempujo";
  code:  string;
  src:   string;
  sizes: SizeMap;
}

export type CartItem = CartItemPersonalizada | CartItemRunning | CartItemSolidary;

// ── Order item ───────────────────────────────────────────────────
export interface OrderItem {
  id:          string;
  productType: ProductType;
  productName: string;
  providerId:  string | null;

  // Per-item production tracking (independent of Order.status)
  productionStatus?: ProductionStatus;

  // --- premium_custom fields ---
  color?:           string;
  phraseCode?:      string;
  designCode?:      string;
  designCategory?:  string;

  // --- running_fullprint fields ---
  printZones?:   PrintZone[];
  finalPreview?: string;    // composite mockup/render code

  // --- solidary_standard fields ---
  itemCode?: string;

  // --- common ---
  sizes:     SizeMap;
  quantity:  number;   // total units
  unitPrice: number;   // cents
  subtotal:  number;   // cents (unitPrice × quantity)
}

// ── Order ────────────────────────────────────────────────────────
export interface ShippingAddress {
  name:        string;
  line1:       string;
  line2?:      string;
  city:        string;
  postal_code: string;
  state?:      string;
  country:     string;
}

export interface Order {
  id:               string;   // uuid
  orderRef:         string;   // BN-2026-000124
  stripeSessionId:  string;
  status:           OrderStatus;
  customerName:     string;
  customerEmail:    string;
  customerPhone?:   string;
  shippingAddress?: ShippingAddress;
  shippingOption?:  string;   // 'Envío estándar' | 'Envío urgente'
  items:            OrderItem[];
  subtotalAmount:   number;   // cents
  shippingAmount:   number;   // cents
  totalAmount:      number;   // cents
  currency:         string;
  // Asset snapshots — frozen at purchase time
  frozenAssets?:    FrozenAsset[];
  // Production PDF paths — one per provider (providerId → absolutePath)
  productionPdfs?:  Record<string, string>;
  createdAt:        string;   // ISO8601
  updatedAt:        string;   // ISO8601
}

// ── Provider ─────────────────────────────────────────────────────
export interface StripeConnectStatus {
  payoutsEnabled:   boolean;
  chargesEnabled:   boolean;
  detailsSubmitted: boolean;
  lastSyncedAt:     string;  // ISO8601
}

export interface Provider {
  id:                    string;
  name:                  string;
  email:                 string;
  stripeAccountId?:      string;         // Stripe Connect Express account
  stripeConnectStatus?:  StripeConnectStatus;
  active:                boolean;
  supportedProductTypes: ProductType[];
  feePercent:            number;         // BENOT margin kept (0-100)
  createdAt:             string;
}

// ── Payout record ────────────────────────────────────────────────
export interface Payout {
  id:                string;
  orderId:           string;
  providerId:        string;
  amount:            number;   // cents sent to provider
  stripeTransferId?: string;
  status:            "pending" | "transferred" | "failed";
  createdAt:         string;
}

// ── Pending cart (stored before Stripe checkout) ──────────────────
export interface PendingCart {
  sessionId: string;
  cart:      CartItem[];
  createdAt: string;
}
