/* ─────────────────────────────────────────────────────────────────
   BENOT Platform — Shared type definitions
   ─────────────────────────────────────────────────────────────── */

// ── Product ──────────────────────────────────────────────────────
export type ProductType =
  | "premium_custom"      // Camiseta personalizada (color + frase + diseño)
  | "running_fullprint"   // Camiseta multideporte 100% fullprint personalizada
  | "solidary_standard";  // Camiseta solidaria #YoTeEmpujo

export const PRODUCT_TYPE_NAMES: Record<ProductType, string> = {
  premium_custom:    "Camiseta personalizada premium",
  running_fullprint: "Camiseta multideporte 100% fullprint personalizada",
  solidary_standard: "Camiseta personalizada estándar",
};

// ── Order lifecycle ───────────────────────────────────────────────
export type OrderStatus =
  | "pending"          // sesión Stripe creada, no pagada
  | "paid"             // pago confirmado por webhook
  | "production_sent"  // email enviado al proveedor
  | "in_production"    // proveedor ha confirmado recepción
  | "shipped"          // en camino
  | "delivered";       // entregado

// ── Sizes map ────────────────────────────────────────────────────
export type SizeMap = Record<string, number>;

// ── Print zone ───────────────────────────────────────────────────
// Models a named area of the garment that receives an independent
// print/design. Extend zoneId with new literals as needed.
//
// Known zone IDs:
//   "front"        – Delante
//   "back"         – Detrás
//   "right_sleeve" – Manga derecha (siempre lleva el logo B de BENOT)
//   "left_sleeve"  – Manga izquierda (reservado)
//   "neck_label"   – Etiqueta interior (reservado)
//   "side_panel"   – Panel lateral (reservado)
export interface PrintZone {
  zoneId:   string;   // unique identifier for the zone
  label:    string;   // human-readable label in Spanish, used in emails
  code:     string;   // asset filename stem (without extension)
  isFixed?: boolean;  // true = non-configurable by the customer (e.g. BENOT logo)
}

// ── Cart items (front-end payload, preserved 1:1) ─────────────────
export interface CartItemPersonalizada {
  tipo:            "personalizada";
  color:           string;
  fraseCode:       string;
  disenoCode:      string;
  disenoCategoria: string;
  sizes:           SizeMap;
}

// Running fullprint: each print zone is stored independently.
// The right sleeve always contains the BENOT "B" logo (isFixed: true).
// finalPreview is the composite mockup generated by the configurador.
export interface CartItemRunning {
  tipo:           "running";
  zones:          PrintZone[];
  finalPreview?:  string;   // asset code for the final composite render
  sizes:          SizeMap;
}

// Solidary (yoteempujo): single fixed design, no zone breakdown needed.
export interface CartItemSolidary {
  tipo:  "yoteempujo";
  code:  string;
  src:   string;
  sizes: SizeMap;
}

export type CartItem = CartItemPersonalizada | CartItemRunning | CartItemSolidary;

// ── Order item ───────────────────────────────────────────────────
export interface OrderItem {
  id:          string;
  productType: ProductType;
  productName: string;
  providerId:  string | null;

  // --- premium_custom fields ---
  color?:           string;
  phraseCode?:      string;
  designCode?:      string;
  designCategory?:  string;

  // --- running_fullprint fields ---
  // Each zone stored individually; zoneId drives asset lookup and
  // email layout. Add future zones here without touching the schema.
  printZones?:   PrintZone[];
  finalPreview?: string;    // composite mockup/render code

  // --- solidary_standard fields ---
  itemCode?: string;

  // --- common ---
  sizes:     SizeMap;
  quantity:  number;   // total units
  unitPrice: number;   // cents
  subtotal:  number;   // cents (unitPrice × quantity)
}

// ── Order ────────────────────────────────────────────────────────
export interface ShippingAddress {
  name:        string;
  line1:       string;
  line2?:      string;
  city:        string;
  postal_code: string;
  state?:      string;
  country:     string;
}

export interface Order {
  id:               string;   // uuid
  orderRef:         string;   // BN-2026-000124
  stripeSessionId:  string;
  status:           OrderStatus;
  customerName:     string;
  customerEmail:    string;
  customerPhone?:   string;
  shippingAddress?: ShippingAddress;
  shippingOption?:  string;   // 'Envío estándar' | 'Envío urgente'
  items:            OrderItem[];
  subtotalAmount:   number;   // cents
  shippingAmount:   number;   // cents
  totalAmount:      number;   // cents
  currency:         string;
  createdAt:        string;   // ISO8601
  updatedAt:        string;   // ISO8601
}

// ── Provider ─────────────────────────────────────────────────────
export interface Provider {
  id:                    string;
  name:                  string;
  email:                 string;
  stripeAccountId?:      string;   // Stripe Connect Express account
  active:                boolean;
  supportedProductTypes: ProductType[];
  feePercent:            number;   // BENOT margin kept (0-100)
  createdAt:             string;
}

// ── Payout record ────────────────────────────────────────────────
export interface Payout {
  id:                string;
  orderId:           string;
  providerId:        string;
  amount:            number;   // cents sent to provider
  stripeTransferId?: string;
  status:            "pending" | "transferred" | "failed";
  createdAt:         string;
}

// ── Pending cart (stored before Stripe checkout) ──────────────────
export interface PendingCart {
  sessionId: string;
  cart:      CartItem[];
  createdAt: string;
}
